/*
 * WeatherAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.weatherapi.api;


import android.content.res.Resources;

public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://api.weatherapi.com/v1";

    //TODO: Replace the key with an appropriate value
    public static String key = "d10e3f778a7444c9a06170205230204";//Resources.getSystem().getString(R.string.WEATHER_API_KEY);

}
